Mandrel Integration TS to tests images

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -2,13 +2,13 @@ name: Build
 
 on:
   pull_request:
-      branches:
-        - main
+    branches:
+      - main
   push:
-      branches:
-        - main
-      paths-ignore:
-        - '.build/**'
+    branches:
+      - main
+    paths-ignore:
+      - '.build/**'
 
 jobs:
   build-images:
@@ -33,84 +33,84 @@ jobs:
           - name: "mandrel builder images (23.0.x)"
             modules: "quarkus-mandrel-builder-image"
             args: "-Pmandrel-23.0.x"
-#          - name: "mandrel builder images (22.x)"
-#            modules: "quarkus-mandrel-builder-image"
-#            args: "-Pmandrel-22.x"
-#          - name: "graalvm ce builder images (latest)"
-#            modules: "quarkus-graalvm-builder-image"
-#            args: ""
-#          - name: "graalvm ce builder images 22.x"
-#            modules: "quarkus-graalvm-builder-image"
-#            args: "-Pgraalvm-22.x"
+    #          - name: "mandrel builder images (22.x)"
+    #            modules: "quarkus-mandrel-builder-image"
+    #            args: "-Pmandrel-22.x"
+    #          - name: "graalvm ce builder images (latest)"
+    #            modules: "quarkus-graalvm-builder-image"
+    #            args: ""
+    #          - name: "graalvm ce builder images 22.x"
+    #            modules: "quarkus-graalvm-builder-image"
+    #            args: "-Pgraalvm-22.x"
 
     steps:
-#    - name: Re-claim some disk space
-#      run: |
-#        sudo swapoff -a
-#        sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android \
-#        /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup
-#        sudo apt-get clean
-#        yes | docker system prune -a
-#        df -h
-    - uses: actions/checkout@v1
-    - uses: actions/setup-java@v3
-      with:
-        distribution: 'temurin'
-        java-version: '17'
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
-      with:
-        platforms: amd64,arm64
-    - name: Set up Docker Buildx
-      id: buildx
-      uses: docker/setup-buildx-action@v3
-      with:
-        install: true
-    - name: Inspect builder
-      run: |
-        echo "Name:      ${{ steps.buildx.outputs.name }}"
-        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
-        echo "Status:    ${{ steps.buildx.outputs.status }}"
-        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
-        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
-    - name: Build ${{ matrix.name }}
-      run: mvn install --projects ${{ matrix.modules }} --also-make -DskipTests ${{ matrix.args }}
-    - name: Test ${{ matrix.name }}
-      env:
-        DOCKER_GHA_BUILDX: true
-      run: |
-        set -x
-        set +e
-        # Deal with spaces in image descriptions
-        NM="${{ matrix.name }}"
-        NM="${NM// /_}"
-        # DOCKER_GHA_SUMMARY_NAME is used in the testsuite
-        export DOCKER_GHA_SUMMARY_NAME=testsuite-logs-${NM}.txt
-        echo "DOCKER_GHA_SUMMARY_NAME=${DOCKER_GHA_SUMMARY_NAME}" >> "$GITHUB_ENV"
-        EXIT_CODE=0
-        # GraalVM CE builder images should work too, merely saving time here...
-        if [[ "${{ matrix.modules }}" == quarkus-mandrel* ]]; then
-          echo "┌── Testing ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
-          mvn install --projects ${{ matrix.modules }} --also-make -DskipTests -Ptest ${{ matrix.args }}
-          EXIT_CODE=$?
-          if [[ $EXIT_CODE -ne 0 ]]; then
-            echo "└── Done with errors: ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
+      #    - name: Re-claim some disk space
+      #      run: |
+      #        sudo swapoff -a
+      #        sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android \
+      #        /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup
+      #        sudo apt-get clean
+      #        yes | docker system prune -a
+      #        df -h
+      - uses: actions/checkout@v1
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+        with:
+          platforms: amd64,arm64
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          install: true
+      - name: Inspect builder
+        run: |
+          echo "Name:      ${{ steps.buildx.outputs.name }}"
+          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
+          echo "Status:    ${{ steps.buildx.outputs.status }}"
+          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
+          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
+      #    - name: Build ${{ matrix.name }}
+      #      run: mvn install --projects ${{ matrix.modules }} --also-make -DskipTests ${{ matrix.args }}
+      - name: Test ${{ matrix.name }}
+        env:
+          DOCKER_GHA_BUILDX: true
+        run: |
+          set -x
+          set +e
+          # Deal with spaces in image descriptions
+          NM="${{ matrix.name }}"
+          NM="${NM// /_}"
+          # DOCKER_GHA_SUMMARY_NAME is used in the testsuite
+          export DOCKER_GHA_SUMMARY_NAME=testsuite-logs-${NM}.txt
+          echo "DOCKER_GHA_SUMMARY_NAME=${DOCKER_GHA_SUMMARY_NAME}" >> "$GITHUB_ENV"
+          EXIT_CODE=0
+          # GraalVM CE builder images should work too, merely saving time here...
+          if [[ "${{ matrix.modules }}" == quarkus-mandrel* ]]; then
+            echo "┌── Testing ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
+            mvn install --projects ${{ matrix.modules }} --also-make -DskipTests -Ptest ${{ matrix.args }}
+            EXIT_CODE=$?
+            if [[ $EXIT_CODE -ne 0 ]]; then
+              echo "└── Done with errors: ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
+            else
+              echo "└── Done: ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
+            fi
           else
-            echo "└── Done: ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
+            echo "═╡ SKIPPED: Testing ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
           fi
-        else
-          echo "═╡ SKIPPED: Testing ${{ matrix.name }}" >> ${DOCKER_GHA_SUMMARY_NAME}
-        fi
-        exit $EXIT_CODE
-    - name: Upload test summary
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ env.DOCKER_GHA_SUMMARY_NAME }}
-        path: ${{ github.workspace }}/${{ env.DOCKER_GHA_SUMMARY_NAME }}
-    - name: Print ${{ matrix.name}}
-      if: always()
-      run: docker images
+          exit $EXIT_CODE
+      - name: Upload test summary
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.DOCKER_GHA_SUMMARY_NAME }}
+          path: ${{ github.workspace }}/${{ env.DOCKER_GHA_SUMMARY_NAME }}
+      - name: Print ${{ matrix.name}}
+        if: always()
+        run: docker images
 
   post-process-summary:
     name: Summary
@@ -151,7 +151,7 @@ jobs:
           echo "{\"pr_number\":\"$PR_NUMBER\",\"org\":\"$ORG_NAME\",\"repo\":\"$REPO_NAME\",\"comment_body\":$COMMENT_JSON_STRING}" > comment-data.json
       - name: Upload comment data
         if: always() && github.event_name == 'pull_request'
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: comment-data-${{ github.event.pull_request.number }}
           path: comment-data.json
